version: '3.7'
services:
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - ./backend/data:/data/db
  nextjs-blogsite:
    build:
      context: frontend
    container_name: blogsite
    restart: always
    depends_on:
      - mongodb_container
    ports:
      - "3000:3000"

  nginx-proxy:
    image: nginx
    ports:
      - "8080:80"


